### ISSUE TITLE
能否提供所使用的segformer预训练节点？

### ISSUE THREAD

**Issue by DLUTTengYH** [zmoka-zht/BiFA#1]
作者您好，我发现代码训练时中需要load segformer的预训练权重，然而segformer的在不同数据集上有不同的预训练权重，请问您使用的是什么权重，可以提供一下节点吗？

**Comment by zmoka-zht** [comment]
感谢您的提问。Segformer的权重已经上传到百度网盘（https://pan.baidu.com/share/init?surl=zxet_fQy6eZZQS3Ak9ChlQ，Code:i81p）。您也可以通过README中的链接进行下载。
