### ISSUE TITLE
关于测试指标

### ISSUE THREAD

**Issue by HuQ1an** [zmoka-zht/BiFA#2]
作者你好，感谢开源代码。关于测试指标我有一些疑问，请问 F1_0，F1_1，recall_0，recall_1这些指标的下缀_0 _1分别指代什么？论文里 report 的似乎是 F1_1

**Comment by zmoka-zht** [comment]
指标的下缀_0 _1分别表示变化的类别和未变化的类别。如果对你有帮助，请star我们。谢谢。

**Comment by HuQ1an** [comment]
@zmoka-zht  感谢回复，Bifa的开源代码对我很有帮助，已经Star。另外想问一下作者在模型训练过程中有没有遇到效果波动的现象？同样的模型在一样的种子设定下，效果差异波动比较大（比如F1指标相差1%以上），不知道这是什么原因引起的？
