### ISSUE TITLE
Need data

### ISSUE THREAD

**Issue by wynotlike** [zmoka-zht/BiFA#4]
Dear Dr./Professor [Haotian Zhang],

I recently came across your paper titled “[BIFA]” and was particularly interested in the LEVIR dataset you have made available. I believe this dataset would be extremely valuable for my ongoing research.

I would be very grateful if you could provide access to the LEVIR dataset. If you require any additional information or clarification, please do not hesitate to let me know.

Thank you for considering my request. I look forward to hearing from you.

Best regards,
[347605528@qq.com]
[2024.12.7]

**Comment by zmoka-zht** [comment]
Thanks for your interest, we have updated the link to the LEVIR dataset. If it helps you, please star us.
